/*
 * Generate the bundled brand-icon map from simple-icons.
 *
 *   node scripts/make-icons.mjs
 *
 * simple-icons ships ~3,500 icons and 16 MB unpacked; bundling it whole would
 * dwarf the app. This picks the domains people actually keep passwords for and
 * emits only those paths, into a module the app loads lazily so the initial
 * bundle is unaffected.
 *
 * Icons are CC0-1.0. The marks remain their owners' trademarks and are used
 * here only to identify the service an entry belongs to, which is what
 * trademark law calls nominative use.
 *
 * To cover something new, add the domain to DOMAINS. The slug is derived from
 * the domain; override it with "domain=slug" where they differ.
 */
import * as si from 'simple-icons';
import { writeFileSync } from 'node:fs';

const DOMAINS = `
google.com amazon.com amazon.co.uk apple.com icloud.com microsoft.com=microsoft
outlook.com github.com gitlab.com bitbucket.org=bitbucket facebook.com
instagram.com x.com=x twitter.com=x linkedin.com reddit.com pinterest.com
tiktok.com snapchat.com whatsapp.com telegram.org=telegram signal.org=signal
discord.com slack.com zoom.us=zoom teams.microsoft.com=microsoftteams
netflix.com spotify.com youtube.com twitch.tv=twitch soundcloud.com
disneyplus.com primevideo.com=primevideo hulu.com deezer.com tidal.com
paypal.com stripe.com wise.com revolut.com monzo.com starling.com=starlingbank
coinbase.com binance.com kraken.com ebay.com etsy.com shopify.com
aliexpress.com alibaba.com walmart.com target.com ikea.com argos.co.uk
asda.com tesco.com sainsburys.co.uk=sainsburys deliveroo.co.uk=deliveroo
ubereats.com justeat.co.uk=justeat uber.com lyft.com airbnb.com booking.com
expedia.com ryanair.com easyjet.com britishairways.com=britishairways
dropbox.com box.com drive.google.com=googledrive onedrive.live.com=microsoftonedrive
mega.nz=mega protonmail.com=protonmail proton.me=proton mail.com fastmail.com=fastmail
tutanota.com=tutanota zoho.com namecheap.com godaddy.com cloudflare.com
digitalocean.com linode.com vercel.com netlify.com heroku.com aws.amazon.com=amazonwebservices
azure.microsoft.com=microsoftazure cloud.google.com=googlecloud docker.com
npmjs.com=npm pypi.org=pypi stackoverflow.com medium.com dev.to=devdotto
notion.so=notion obsidian.md=obsidian evernote.com todoist.com trello.com
asana.com monday.com jira.atlassian.com=jira confluence.atlassian.com=confluence
figma.com canva.com adobe.com behance.net=behance dribbble.com unsplash.com
steampowered.com=steam epicgames.com gog.com playstation.com xbox.com
nintendo.com roblox.com minecraft.net=minecraft ea.com ubisoft.com
wikipedia.org openai.com anthropic.com huggingface.co=huggingface
duckduckgo.com brave.com mozilla.org=mozilla firefox.com=firefox
nordvpn.com expressvpn.com protonvpn.com=protonvpn mullvad.net=mullvad
bitwarden.com 1password.com lastpass.com keepassxc.org=keepassxc
nextcloud.com synology.com plex.tv=plex jellyfin.org=jellyfin sonarr.tv=sonarr
radarr.video=radarr homeassistant.io=homeassistant tailscale.com
wordpress.com squarespace.com wix.com webflow.com mailchimp.com
substack.com patreon.com kofi.com=kofi buymeacoffee.com gumroad.com
coursera.org udemy.com duolingo.com khanacademy.org=khanacademy
strava.com fitbit.com garmin.com myfitnesspal.com nike.com adidas.com
spotify.com last.fm=lastdotfm bandcamp.com vimeo.com flickr.com
imgur.com giphy.com archive.org=internetarchive letterboxd.com
goodreads.com audible.com kobo.com scribd.com
`.trim().split(/\s+/);

const bySlug = new Map();
for (const icon of Object.values(si)) {
  if (icon && icon.slug) bySlug.set(icon.slug, icon);
}

const slugFor = (domain) =>
  domain.replace(/\.(com|org|net|io|co\.uk|tv|me|so|md|nz|us|dev|to|video|fm)$/i, '')
    .replace(/[^a-z0-9]/gi, '')
    .toLowerCase();

const out = {};
const missing = [];
for (const entry of DOMAINS) {
  const [domain, override] = entry.split('=');
  const icon = bySlug.get(override || slugFor(domain));
  if (!icon) { missing.push(entry); continue; }
  out[domain] = { p: icon.path, c: icon.hex };
}

const sorted = Object.keys(out).sort();
const body = sorted.map((d) => `  ${JSON.stringify(d)}: ${JSON.stringify(out[d])},`).join('\n');

writeFileSync('src/lib/icondata.ts', `/*
 * GENERATED by scripts/make-icons.mjs — do not edit by hand.
 *
 * Brand marks from simple-icons (CC0-1.0). Trademarks remain their owners';
 * they appear here only to identify the service an entry belongs to.
 *
 * Imported dynamically so none of this lands in the initial bundle.
 */
export interface BrandIcon { p: string; c: string }

export const BRAND_ICONS: Record<string, BrandIcon> = {
${body}
};
`);

console.log(`wrote src/lib/icondata.ts — ${sorted.length} icons`);
if (missing.length) console.log(`no simple-icons match for: ${missing.join(' ')}`);
